[2025-04-03T09:09:54.934+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-04-03T09:09:53.189118+00:00 [queued]>
[2025-04-03T09:09:54.940+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-04-03T09:09:53.189118+00:00 [queued]>
[2025-04-03T09:09:54.940+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-04-03T09:09:54.941+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-04-03T09:09:54.941+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-04-03T09:09:54.951+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-04-03 09:09:53.189118+00:00
[2025-04-03T09:09:54.956+0000] {standard_task_runner.py:55} INFO - Started process 6046 to run task
[2025-04-03T09:09:54.958+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-04-03T09:09:53.189118+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpav43zovw']
[2025-04-03T09:09:54.960+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask is_api_available
[2025-04-03T09:09:54.992+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-04-03T09:09:53.189118+00:00 [running]> on host dd456f953b15
[2025-04-03T09:09:55.062+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-04-03T09:09:53.189118+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-03T09:09:53.189118+00:00
[2025-04-03T09:09:55.064+0000] {http.py:120} INFO - Poking: api/
[2025-04-03T09:09:55.077+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-04-03T09:09:55.083+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-04-03T09:09:55.754+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-04-03T09:09:55.800+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250403T090953, start_date=20250403T090954, end_date=20250403T090955
[2025-04-03T09:09:55.848+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-04-03T09:09:55.875+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
